title: Birol Cabukusta
url: "birolcabukusta.github.io"


markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
#footer_url: "https://github.com/ankitsultana"
footer_text: "Maastricht University | M4i â€“ Maastricht Multimodal Molecular Imaging Institute"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "research"
 - name: "Publications"
   link: "publications"
 - name: "Contact"
   link: "contact"
