# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: title
email: email
remote_theme: ankitsultana/researcher@gem
description: > # this means to ignore newlines until "baseurl:"
  Website of the Uppsala Secure Learning and Control Lab.
baseurl: ""
url: "https://uslc-lab.github.io"

include:
  - .htaccess
  - _pages

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
