# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Researcher
url: "https://ankitsultana.com"
remote_theme: ankitsultana/researcher@gem


markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Research"
   link: "research.md"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
